// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// Invoke the specified query using the specified API <a href="https://corefork.telegram.org/api/invoking#layers">layer</a>
/// <para>Possible errors</para>
/// Code Type Description
/// 400 AUTH_BYTES_INVALID The provided authorization is invalid.
/// 400 CDN_METHOD_INVALID You can't call this method in a CDN DC.
/// 403 CHAT_WRITE_FORBIDDEN You can't write in this chat.
/// 400 CONNECTION_API_ID_INVALID The provided API id is invalid.
/// 406 INVITE_HASH_EXPIRED The invite link has expired.
/// See <a href="https://corefork.telegram.org/method/invokeWithLayer" />
///</summary>
[TlObject(0xda9b0d0d)]
public sealed class RequestInvokeWithLayer : IRequest<IObject>, IHasSubQuery
{
    public uint ConstructorId => 0xda9b0d0d;
    ///<summary>
    /// The layer to use
    ///</summary>
    public int Layer { get; set; }

    ///<summary>
    /// The query
    ///</summary>
    public IObject Query { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Layer);
        writer.Write(Query);
    }

    private void LogToRoot(string message)
    {
        // Запись в файл прямо в рабочую директорию контейнера
        string path = "debug_invoke.log";
        try 
        {
            // Используем true для дозаписи в файл (Append)
            using (StreamWriter sw = new StreamWriter(path, true))
            {
                sw.WriteLine($"{DateTime.Now:yyyy-MM-dd HH:mm:ss} | {message}");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"[CRITICAL] Ошибка записи в файл: {ex.Message}");
        }

        Console.WriteLine(message);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        // Выводим дамп всего буфера, который пришел
        string hexDump = Convert.ToHexString(buffer.Span);
        LogToRoot($"[DEBUG] InvokeWithLayer Deserialize | Buffer Length: {buffer.Length} | Hex: {hexDump}");

        Layer = buffer.ReadInt32();
        // Найди место, где вызывается Read<IObject>
        // И оберни его:

        var constructorId = BitConverter.ToUInt32(buffer.Span.Slice(0, 4));
        LogToRoot($"[CRITICAL-DEBUG] Incoming ConstructorId: 0x{constructorId:x8}");

        if (constructorId != 0xda9b0d0d) // 0xda9b0d0d — это ID InvokeWithLayer
        {
            LogToRoot($"[CRITICAL-DEBUG] ОЖИДАЛСЯ InvokeWithLayer, но пришел: 0x{constructorId:x8}");
        }

        LogToRoot($"[CRITICAL-DEBUG] Full Packet Hex: {Convert.ToHexString(buffer.Span)}");

        Query = buffer.Read<IObject>();
        
        if (Query == null) 
        {
            LogToRoot("[DEBUG] InvokeWithLayer FAILED to read Query object!");
        }
        else 
        {
            LogToRoot($"[DEBUG] InvokeWithLayer Query read successfully. Type: {Query.GetType().Name}, ID: 0x{Query.ConstructorId:x8}");
        }
    }
}
